spring:
  application:
    name: zuishare-member
  datasource:
    druid:
      url: ${jdbc.url}
      username: ${jdbc.username}
      password: ${jdbc.password}
      driver-class-name: com.mysql.jdbc.Driver
      initial-size: 5
      max-active: 8
      pool-prepared-statements: false
      max-open-prepared-statements: -1
      validation-query: select 'x'
      validation-query-timeout: 5
      test-while-idle: true
  profiles:
    active: mac_local
  http:
    encoding:
      force: true
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
    mode: HTML5
    encoding: UTF-8
    content-type: text/html
    cache: false
  mvc:
    favicon:
      enabled: false
# Redis数据库索引（默认为0）
  redis:
    database: 0
# Redis服务器地址
    host: localhost
# Redis服务器连接端口
    port: 6380
# Redis服务器连接密码（默认为空）
    password:
# 连接池最大连接数（使用负值表示没有限制）
    pool:
      max-active: 15
# 连接池最大阻塞等待时间（使用负值表示没有限制）
      max-wait: -1
# 连接池中的最大空闲连接
      max-idle: 10
# 连接池中的最小空闲连接
      min-idle: 5
# 连接超时时间（毫秒）
    timeout: 1000

mybatis:
  type-aliases-package: top.zuishare.spi.model
  mapper-locations: classpath:mybatis/*Mapper.xml
  configuration:
    map-underscore-to-camel-case: true
    default-fetch-size: 100
    default-statement-timeout: 30

zuishare:
  picPath: ${pic.path}
  hotLimit: ${hot.limit}
  companyConfigPath: ${company.config.path}
  webConfigPath: ${web.config.path}
  indexAds: ${index.ad.limit}
  indexProductsSize: ${index.products.limit}

server:
  port: 8081
---
spring:
  profiles: win_local
server:
  port: 8082
---
spring:
  profiles: mac_local
server:
  port: 8082
---
spring:
  profiles: prd
server:
  port: 8080